# Akses Localhost dengan Python

Pada pertemuan sebelumnya telah depelajari pengenalan dasar bagaimana mengakses basis data dengan menggunakan Python ke MySQL dan PostgreSQL. Pada pertemuan kedua ini, akan fokus untuk berlatih untuk melakukan pemilihan data. Secara garis besar materi yang akan dibahas adalah; 

* Mengulang kembali bagaimana meng-akses basis data dengan Python ke MySQL dan PostgreSQL
* Membuat dan menghapus basis data
* Membuat database lengkap dengan melakukan import data dari Excel **(database rekayasa untuk pelatihan Data Analytics di JNE)**
* Operasi tabel pada database
* Menambahkan pengaturan batasan tabel 


## Koneksi MySQL dan Python

Untuk mengakses basis data yang ada pada MySQL dengan Python dapat menggunakan koding berikut di Jupiterlab anda. 

```{r include=FALSE}
library(reticulate)
library(Rcpp)
# conda_list()
use_condaenv("base", required = TRUE)
```

```{python, eval=F}
# import module 
import mysql.connector

# koneksi server
db1 = mysql.connector.connect(
  host='localhost',
  user='bakti',
  passwd='123'
)
```

Jika tidak muncul pesan error pada saat menjalankan koding diatas pada Chunck Jupiterlab anda. Artinya, koneksi Python ke MySQL sudah terhubung dengan baik. 

### Memeriksa Daftar Database

Setelah kita terhubung dengan local server menggunakan Python dan MySQL. Sekarang saatnya kita mulai untuk memerikas database apa saja yang ada didalamnya. 

```{python, eval=F}
# membuat objek 'cursor` sebagai kata kunci eksekusi SQL
cursor1 = db1.cursor()

# Perintah SQL
sql = 'SHOW DATABASES'

# Eksekusi perintah  SQL
cursor1.execute(sql)

# menampilkan daftar database
for x in cursor1:
  print(x) 
```

### Membuat Database

Berikut ini adalah koding yang dapat digunakan untuk membuat database baru dengan menggunakan koneksi `db.cursor()` yang ada pada objek `cursor`.

```{python, eval=F}
sql= 'CREATE DATABASE jne2'
cursor1.execute(sql)
```


### Menghapus Database 

Jika anda ingin menghapus database tertentu dari lokal server, maka dapat melakukannya dengan koding berikut:

```{python, eval=F}
sql= 'DROP DATABASE jne2'
cursor1.execute(sql)
```


### Memeriksa Daftar Tabel

Untuk memeriksa daftar tabel yang ada pada local server. Perhatikan Koding berikut:

```{python, eval=F}
# import module 
import mysql.connector

# koneksi salah satu database MySQl ke Python
db2 = mysql.connector.connect(
  host='localhost',
  user='bakti',
  passwd='123',
  database='jne2'
)

# membuat objek 'cursor` sebagai kata kunci eksekusi SQL
cursor2 = db2.cursor()

# Perintah SQL
sql = "SHOW TABLES"

# Eksekusi perintah  SQL
cursor2.execute(sql)

# menampilkan daftar tabel
for x in cursor2:
  print(x) 
```



## CRUDS Lanjut 

Pada materi sebelumnya telah dipelajari bagaimana untuk melakukan `CRUDS` database. `CRUDS` merupakan singkatan dari **Create, Read, Update, Delete, dan Search**. Berikut ini akan diperlihatkan cara untuk menambahkan daftar database dari CSV. Langkah pertama, import data dari Excel menggukan Python.

```{python, eval=F}
import pandas as pd

link_data = 'https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/users.csv'

df1 = pd.read_csv(link_data, sep=';' )
df1.head(5)
```

### `Create` Tabel dari CSV 

Jika data tabel yang telah di import dari file CSV sudah ada dalam memori Jupeterlab **(Python)** anda, maka selanjutnya untuk menambahkan tabel tersebut ke database adalah sebagai berikut:

```{python, eval=F}
import pymysql
from sqlalchemy import create_engine

# membuat engine
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="bakti",
                               pw="123",
                               db="jne2"))

# df1.to_sql('users', engine, if_exists = 'append', index = True)
df1.to_sql('user', engine, if_exists='replace', index = False)
```

**Tugas Kelompok:**

Tambahkan tabel berikut ke database `jne2` dengan mengikuti materi yang sudah anda pelajari sebelumnya. 

* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/products.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/products.csv)
* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/orders.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/orders.csv)
* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/order_items.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/order_items.csv)
* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/inventory_items.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/inventory_items.csv)
* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/events.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/events.csv)
* [https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/distribution_centers.csv](https://raw.githubusercontent.com/dsciencelabs/JNE_Data_Analytics_PySQL/main/data/data_latihan/distribution_centers.csv)


### `Read` Dataframe

Berbeda dengan materi materi dasar yang kita pelajari sebelumnya, untuk membaca data tabel dari database dalam bentuk dataframe dapat dilakukan dengan cara berikut;

```{python, eval=F}
import pandas as pd

en_co = engine.connect()

df2 = pd.read_sql_table('distribution_centers', en_co)
df2
```

### Update Data Tabel 

Sama seperti yang telah dipelajari sebelumnya, melakukan update data pada tabel disini dapat dilakukan dengan cara berikut:

```{python, eval=F}
sql = 'UPDATE distribution_centers SET name=%s, latitude=%s, longitude=%s WHERE id=%s'
val = ("JNE Learning Center", 106.7977, -6.1774, 10)
cursor2.execute(sql, val)

db2.commit()

print("{} data diubah".format(cursor2.rowcount))
```

**Tugas Kelompok:**

* Tambahkan satu lokasi baru pada tabel `distribution_centers`
* Tambahkan tiga lokasi baru pada tabel `distribution_centers`

```{python, eval=F}
sql = '''INSERT INTO karyawan (
                     name=%s, 
                     latitude=%s, 
                     longitude=%s) 
       VALUES (%s, %s, %s)'''
val = ("JNE", 106.7977, -6.1774)
cursor2.execute(sql, val)

db2.commit()

print('{} data ditambahkan'.format(cursor2.rowcount))
```


### Delete 


### Search

## Mengubah Tabel 

Ada kalanya kita ingin menambah, memodifikasi, menghapus yang ada pada tabel. Pernyataan yang digunakan adalah `ALTER TABLE`, seperti diperlihatkan sebagai berikut:


### Menambah Kolom

```{python}

```











